2023-03-15 17:32:03,191 [INFO   ] [APP] exchange started with arguments={rtg.py, run, autotrader.py}
2023-03-15 17:32:03,191 [INFO   ] [APP] configuration={"Engine":{"MarketDataFile":"data/market_data1.csv","MarketEventInterval":0.05,"MarketOpenDelay":5.0,"MatchEventsFile":"match_events.csv","ScoreBoardFile":"score_board.csv","Speed":1.0,"TickInterval":0.25},"Execution":{"Host":"127.0.0.1","Port":12345},"Fees":{"Maker":-0.0001,"Taker":0.0002},"Hud":{"Host":"127.0.0.1","Port":12347},"Information":{"Type":"mmap","Name":"info.dat"},"Instrument":{"EtfClamp":0.002,"TickSize":1.0},"Limits":{"ActiveOrderCountLimit":10,"ActiveVolumeLimit":200,"MessageFrequencyInterval":1.0,"MessageFrequencyLimit":50,"PositionLimit":100},"Traders":{"TraderOne":"secret","TraderTwo":"secret"}}
2023-03-15 17:32:03,192 [INFO   ] [CONTROLLER] starting the match
2023-03-15 17:32:03,192 [INFO   ] [EXECUTION] starting execution server: host=127.0.0.1 port=12345
2023-03-15 17:32:03,193 [INFO   ] [INFORMATION] starting information publisher: type=mmap name=info.dat
2023-03-15 17:32:03,193 [INFO   ] [HEADS_UP] starting heads-up display server: host=127.0.0.1 port=12347
2023-03-15 17:32:03,195 [INFO   ] [INFORMATION] information channel established
2023-03-15 17:32:03,839 [INFO   ] [CONNECTION] fd=22 connection established: peer=127.0.0.1:40270
2023-03-15 17:32:03,842 [INFO   ] [EXECUTION] fd=22 'TraderOne' is ready!
2023-03-15 17:32:05,107 [INFO   ] [CONNECTION] fd=23 connection established: peer=127.0.0.1:40794
2023-03-15 17:32:08,203 [INFO   ] [CONTROLLER] market open
2023-03-15 17:32:08,215 [INFO   ] [CONNECTION] fd=22 connection lost
2023-03-15 17:32:08,215 [WARNING] [EXECUTION] fd=22 lost connection to auto-trader:
2023-03-15 17:32:19,079 [INFO   ] [APP] SIGTERM signal received - shutting down...
2023-03-15 17:32:19,079 [INFO   ] [APP] closing event loop
2023-03-15 20:16:50,433 [INFO   ] [APP] exchange started with arguments={rtg.py, run, autotrader.py}
2023-03-15 20:16:50,433 [INFO   ] [APP] configuration={"Engine":{"MarketDataFile":"data/market_data1.csv","MarketEventInterval":0.05,"MarketOpenDelay":5.0,"MatchEventsFile":"match_events.csv","ScoreBoardFile":"score_board.csv","Speed":1.0,"TickInterval":0.25},"Execution":{"Host":"127.0.0.1","Port":12345},"Fees":{"Maker":-0.0001,"Taker":0.0002},"Hud":{"Host":"127.0.0.1","Port":12347},"Information":{"Type":"mmap","Name":"info.dat"},"Instrument":{"EtfClamp":0.002,"TickSize":1.0},"Limits":{"ActiveOrderCountLimit":10,"ActiveVolumeLimit":200,"MessageFrequencyInterval":1.0,"MessageFrequencyLimit":50,"PositionLimit":100},"Traders":{"TraderOne":"secret","TraderTwo":"secret"}}
2023-03-15 20:16:50,436 [INFO   ] [CONTROLLER] starting the match
2023-03-15 20:16:50,436 [INFO   ] [EXECUTION] starting execution server: host=127.0.0.1 port=12345
2023-03-15 20:16:50,437 [ERROR  ] [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Controller.start() done, defined at /home/chi/Workspaces/optiver-ready-trader-go-2023/base_autotrader/ready_trader_go/controller.py:102> exception=OSError(98, "error while attempting to bind on address ('127.0.0.1', 12345): address already in use")>
Traceback (most recent call last):
  File "/home/chi/Workspaces/optiver-ready-trader-go-2023/base_autotrader/ready_trader_go/controller.py", line 106, in start
    await self.__execution_server.start()
  File "/home/chi/Workspaces/optiver-ready-trader-go-2023/base_autotrader/ready_trader_go/execution.py", line 185, in start
    self.__server = await asyncio.get_running_loop().create_server(self.__on_new_connection, self.host, self.port)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 12345): address already in use
2023-03-15 20:17:17,455 [INFO   ] [APP] SIGTERM signal received - shutting down...
2023-03-15 20:17:17,456 [INFO   ] [APP] closing event loop
